### PR TITLE
channel plot, small edit to qHKCa

### PR DESCRIPTION
**Pull request by stevevanhooser**
OK, I think we have the final version here. I added my plots of the channels.

Google Drive is down now, so I suppose I have to finish editing the lab itself in the morning.

Best
Steve

### CODE REVIEW

**Comment by sg-s** [comment]
This isn't right --

The exponents play no role in the activation curves. the "activation curves" are just plots of m_inf vs V. the only place the exponents show up is in calculating the currents.

**Comment by stevevanhooser** [comment]
What I’m trying to plot is the open probability (steady state) of a channel (that’s what’s on the label of the axis). There, you need the exponent, right? We haven’t taught them about activation curves, so I’m trying to use terms they understand (open probability is digestible). 

They only learn activation curves if they take Paul Miller’s course, unfortunately...

**Comment by sg-s** [comment]
Ah I see, then it's right. I've added two new functions that plot the activation curves (w/o exponents) in case you want to use that. (also much simpler to plot since it's built in)

**Comment by sg-s** [comment]
I'm going to change your plot func -- it can be a lot simpler since xolotl can do all the calculations for you. hang on...

**Comment by sg-s** [comment]
Hi @stevevanhooser 

I refactored lab5_plotchans to [a new file](https://github.com/sg-s/nbio140-lab5/blob/master/open_probabilities.m) 

It does exactly the same thing but hopefully it will be easier to maintain in the future -- i removed the evals, and the hard-coded functions so it can be adapted to other channels if need be.

**Comment by stevevanhooser** [comment]
Thanks! Cool!

**Pull request merged**
